import type { Article } from "@/types/article";

export const articles: Article[] = [
  {
    id: "1",
    image: "/images/news1.jpg",
    date: "2024-07-20",
    title: "NBC Champions Financial Inclusion at the 48th Dar es Salaam International Trade Fair",
    description: "NBC demonstrated its commitment to financial inclusion by participating in the 48th Dar es Salaam International Trade Fair (DITF), showcasing innovative digital solutions and services.",
    category: "Press Release",
    badgeText: "Featured",
    featured: true,
  },
  {
    id: "2",
    image: "/images/news2.jpg",
    date: "2024-07-19",
    title: "NBC Launches New Mobile Banking App with Enhanced Security Features",
    description: "The new NBC Mobile Banking app offers a seamless user experience with biometric authentication and advanced encryption to protect customer data.",
    category: "Product News",
  },
  {
    id: "3",
    image: "/images/news3.jpg",
    date: "2024-07-18",
    title: "Strategic Partnership with Tigo Pesa to Expand Digital Payment Options",
    description: "NBC has partnered with Tigo Pesa to allow customers to easily transfer funds between their bank accounts and mobile wallets, fostering greater convenience.",
    category: "Partnerships",
  },
  {
    id: "4",
    image: "/images/news4.jpg",
    date: "2024-07-17",
    title: "NBC Announces Annual Marathon to Support Community Health Initiatives",
    description: "The upcoming NBC Annual Marathon aims to raise funds for local hospitals and health centers, promoting wellness and community engagement.",
    category: "Events",
  },
  {
    id: "5",
    image: "/images/recent-product.jpg",
    date: "2024-07-16",
    title: "Market Insights: Tanzanian Shilling Shows Stability Against US Dollar",
    description: "Our latest market analysis reveals that the Tanzanian shilling has maintained stability, supported by strong export performance and prudent fiscal policies.",
    category: "Market Insights",
  },
  {
    id: "6",
    image: "/images/offering.jpg",
    date: "2024-07-15",
    title: "Financial Literacy Workshop for Small and Medium Enterprises (SMEs)",
    description: "NBC hosted a workshop to empower SME owners with financial management skills, covering topics such as budgeting, access to credit, and digital tools.",
    category: "Events",
  },
  {
    id: "7",
    image: "/images/hero1.jpg",
    date: "2024-07-14",
    title: "NBC Awarded 'Best Retail Bank in Tanzania' for the Third Consecutive Year",
    description: "This prestigious award recognizes NBC's excellence in customer service, digital innovation, and commitment to meeting the evolving needs of our clients.",
    category: "Awards",
    badgeText: "Award",
  },
  {
    id: "8",
    image: "/images/hero2.jpg",
    date: "2024-07-13",
    title: "Expansion of Agent Banking Network to Underserved Rural Areas",
    description: "To enhance financial accessibility, NBC is expanding its agent banking network, bringing essential services closer to communities in rural Tanzania.",
    category: "Press Release",
  },
  {
    id: "9",
    image: "/images/news1.jpg",
    date: "2024-07-12",
    title: "NBC Introduces Green Financing for Sustainable Agriculture Projects",
    description: "In line with our sustainability goals, NBC has launched a new loan product to support environmentally friendly agricultural practices and renewable energy.",
    category: "Product News",
  },
  {
    id: "10",
    image: "/images/news2.jpg",
    date: "2024-07-11",
    title: "A Glimpse into the Future of Digital Banking in East Africa",
    description: "Experts at the recent FinTech conference discussed the transformative potential of AI, blockchain, and data analytics in shaping the future of banking.",
    category: "Market Insights",
  },
  {
    id: "11",
    image: "/images/news3.jpg",
    date: "2024-07-10",
    title: "NBC Staff Volunteer Day: Supporting Education in Local Communities",
    description: "Our employees dedicated their time to renovate schools and mentor students as part of our ongoing commitment to corporate social responsibility.",
    category: "CSR",
  },
  {
    id: "12",
    image: "/images/news4.jpg",
    date: "2024-07-09",
    title: "Collaboration with the University of Dar es Salaam to Nurture Tech Talent",
    description: "This partnership will provide internships and training programs for students, bridging the gap between academia and the financial technology industry.",
    category: "Partnerships",
  },
  {
    id: "13",
    image: "/images/recent-product.jpg",
    date: "2024-07-08",
    title: "New Investment Opportunities in Tanzanian Government Bonds",
    description: "NBC is pleased to offer our clients exclusive access to new government bonds, providing a secure and attractive investment for diversifying portfolios.",
    category: "Press Release",
  },
  {
    id: "14",
    image: "/images/offering.jpg",
    date: "2024-07-07",
    title: "Customer Appreciation Week: Celebrating Our Valued Clients",
    description: "Join us for a week of special offers, events, and giveaways as we thank our loyal customers for their continued trust and partnership.",
    category: "Events",
  },
  {
    id: "15",
    image: "/images/hero1.jpg",
    date: "2024-07-06",
    title: "Cybersecurity Awareness Campaign to Protect Customers from Fraud",
    description: "NBC is launching a nationwide campaign to educate customers on how to identify and protect themselves from common online scams and phishing attempts.",
    category: "Press Release",
  },
  {
    id: "16",
    image: "/images/hero2.jpg",
    date: "2024-07-05",
    title: "Analysis of Q2 Economic Performance and Outlook for H2 2024",
    description: "Our economists provide an in-depth analysis of the key economic trends from the second quarter and share their outlook for the remainder of the year.",
    category: "Market Insights",
  },
  {
    id: "17",
    image: "/images/news1.jpg",
    date: "2024-07-04",
    title: "NBC La Riba Islamic Banking Window Expands Product Offerings",
    description: "The La Riba Islamic Banking window has introduced new Shari'ah-compliant products, including Takaful insurance and home financing.",
    category: "Product News",
  },
  {
    id: "18",
    image: "/images/news2.jpg",
    date: "2024-07-03",
    title: "NBC Foundation Scholarship Program Opens for 2024 Applications",
    description: "The NBC Foundation is now accepting applications for its annual scholarship program, supporting bright and underprivileged students in pursuing higher education.",
    category: "CSR",
  },
  {
    id: "19",
    image: "/images/news3.jpg",
    date: "2024-07-02",
    title: "Digital Transformation in the Banking Sector: A Panel Discussion",
    description: "Our CEO joined other industry leaders to discuss the challenges and opportunities of digital transformation at the annual banking summit.",
    category: "Events",
  },
  {
    id: "20",
    image: "/images/news4.jpg",
    date: "2024-07-01",
    title: "NBC Reports Strong Financial Performance in First Half of 2024",
    description: "NBC has announced robust financial results for the first half of the year, driven by growth in our loan portfolio and digital banking services.",
    category: "Press Release",
  },
]; 